services:
    contao.config:
        class: Contao\Config
        factory_class: Contao\Config
        factory_method: getInstance

    contao.routing_loader:
        class:     Contao\Bundle\CoreBundle\Config\Loader\ContaoLoader
        arguments: ['@contao.config']
        tags:
            - { name: routing.loader }

    contao.listener.output_from_cache:
        class:     Contao\Bundle\CoreBundle\EventListener\OutputFromCacheListener
        arguments: ['@contao.config']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    contao.listener.add_to_search_index:
        class:     Contao\Bundle\CoreBundle\EventListener\AddToSearchIndexListener
        arguments: ['@contao.config']
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
