services:
    contao.listener.add_to_search_index:
        class: Contao\CoreBundle\EventListener\AddToSearchIndexListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    contao.listener.container_scope:
        class: Contao\CoreBundle\EventListener\ContainerScopeListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 254 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest, priority: -254 }

    contao.listener.initialize_system:
        class: Contao\CoreBundle\EventListener\InitializeSystemListener
        arguments:
            - "@router"
            - "%kernel.root_dir%"
        tags:
            # Priority must be higher than any other listener that uses the Contao framework and lower than the
            # priority of the route_listener, which defaults to 32.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

    contao.listener.output_from_cache:
        class: Contao\CoreBundle\EventListener\OutputFromCacheListener
        tags:
            # Priority must be lower than the one of the Contao initialize system listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 24 }

    contao.listener.toggle_view:
        class: Contao\CoreBundle\EventListener\ToggleViewListener
        tags:
            # Priority must be lower than the one of the Contao initialize system listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 26 }

    contao.listener.check_request_token:
        class: Contao\CoreBundle\EventListener\CheckRequestTokenListener
        tags:
            # Priority must be lower than the one of the Contao initialize system listener.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 28 }

    contao.routing.backend_loader:
        parent: routing.bundle_resource_loader
        arguments:
            - "@@ContaoCoreBundle/Resources/config/routing.yml"
        tags:
            - { name: routing.bundle_loader, priority: 200 }

    contao.routing.dev_loader:
        parent: routing.bundle_resource_loader
        arguments:
            - "@@ContaoCoreBundle/Resources/config/routing_dev.yml"
            - ["dev", "test"]
        tags:
            - { name: routing.bundle_loader }

    contao.routing.frontend_loader:
        class: Contao\CoreBundle\Routing\FrontendLoader
        arguments:
            - "%prepend_locale%"
            - "%url_suffix%"
            - "%locale%"
        tags:
            - { name: routing.bundle_loader, priority: -250 }

    contao.security.authenticator:
        class: Contao\CoreBundle\Security\ContaoAuthenticator
        public: false
        arguments:
            - "@contao.security.user_provider"

    contao.security.user_provider:
        class: Contao\CoreBundle\Security\User\ContaoUserProvider
        public: false

    contao.web_profiler.data_collector:
        class: Contao\CoreBundle\DataCollector\ContaoDataCollector
        tags:
            - { name: data_collector, template: "ContaoCoreBundle:Collector:contao", id: "contao" }
